services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: back-end
    ports: []
    expose:
      - '5252'

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: front-end
    ports: []
    expose:
      - '9000'
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    ports:
      - '80:80'
    depends_on:
      - back-end
      - front-end
